application: google-appengine-template
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on
- appstats: on
- datastore_admin: on

handlers:
- url: /images
  static_dir: static/images

- url: /stylesheets
  static_dir: static/css

- url: /scripts
  static_dir: static/js

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: favicon\.ico

- url: /data
  static_dir: static/data

- url: .*
  script: main.py
